<a href="https://colab.research.google.com/github/PCsujan/ML_From_Scratch/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas

# New Section

🎯pandas

🖥️Data preprocessing in machine learning usnig pandas
Data reprocessing is required tasks for clearning the data and making it suitable for a machine learning model which also increase the accuracy and efficiency of a machine learnig model.

📺pandas is an open source python packages that is most widely used for data science/data analysis and machine learning tasks. it is built on top of another package named Numpy, which provides support for multi-dimensional arrays.preprocessing is the process of doing a pre-analysis of data,in order to transform them into a standard and normalized format.

🧸pre-processing involves the following aspects.
  - missing values
  - data standardation
  - data normalization
  - data minning

In [ ]:
import pandas as pd


In [ ]:
data = {
    "cars":["bmw", "honda", "suzuki", "BYD"],
    "models": ["2007", "2009", "2008", "2023"],
    "passenger": ["5", "5", "6", "7"]
}
#print(data)
data

{'cars': ['bmw', 'honda', 'suzuki', 'BYD'],
 'models': ['2007', '2009', '2008', '2023'],
 'passenger': ['5', '5', '6', '7']}

In [ ]:
#Covert the data into dataframe
df = pd.DataFrame(data)
df

cars models passenger
0     bmw   2007         5
1   honda   2009         5
2  suzuki   2008         6
3     BYD   2023         7

In [7]:
# save the files as a csv files
df.to_csv("/content/drive/MyDrive/Colab Notebooks/pandas/car_data.csv")

In [8]:
pd.__version__

'2.2.2'

In [10]:
# pandas Series
import pandas as pd
a = [1, 7, 2]
myvar = pd.Series(a)
#print(myvar)
myvar

0    1
1    7
2    2
dtype: int64

In [11]:
# create levels in pandas with index.
a = [1, 7, 2]
myvar = pd.Series(a, index = ["x", "y", "z"])
myvar

x    1
y    7
z    2
dtype: int64

In [13]:
print(myvar["y"])

7


In [14]:
# task : create a dataframe named df, with data calories and duration.
data = {

    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}
df = pd.DataFrame(data)
df

calories  duration
0       420        50
1       380        40
2       390        45

In [15]:
print(df.loc[1])

calories    380
duration     40
Name: 1, dtype: int64


In [17]:
print(df.loc[[1, 2]])

   calories  duration
1       380        40
2       390        45


In [18]:
import pandas as pd
data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}
df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
df

calories  duration
day1       420        50
day2       380        40
day3       390        45

In [20]:
print(df.loc["day2"])

calories    380
duration     40
Name: day2, dtype: int64


DAta Clearning with pandas
bad data can be


## Introduction to numpy
what will we cover?
- creating arrays
- multi diesional array
- randomly generated array
    - element wise operations
    - coparision operations
-LOGICAL operation

summarizing operation

###single dimensional arrays


In [ ]:
import numpy as np

###Multidimesional Arrays

In [ ]:
var = np.zeros(5)
print(type(var))

<class 'numpy.ndarray'>


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
var= np.array([1, 2, 3, 4])
var[2] = 5
var

array([1, 2, 5, 4])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

create array with evenly spaced numbers within a specified
range

In [ ]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [ ]:
np.zeros([5, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
#create a Md unit array of size(5, 2)

np.ones([5, 2])


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#Generate a random array of size (3, 5)with element of your choice
n = np.random.randint(1, 10, size=(3, 5))

n


array([[6, 2, 2, 8, 3],
       [5, 3, 2, 4, 2],
       [6, 9, 9, 6, 4]])

In [ ]:
#upadte the element of array with in index
n[0, 0]= 10
n



array([[10,  2,  2,  8,  3],
       [ 5,  3,  2,  4,  2],
       [ 6,  9,  9,  6,  4]])

In [ ]:
n[0] = [1, 1, 1, 1, 1]
n

array([[1, 1, 1, 1, 1],
       [5, 3, 2, 4, 2],
       [6, 9, 9, 6, 4]])

In [ ]:
n[:,2] = [2, 2, 2]

n


array([[1, 1, 2, 1, 1],
       [5, 3, 2, 4, 2],
       [6, 9, 2, 6, 4]])

###Randomly generated arrays
- Numpy can cratre array filled with random number.
- To ensure the reproducibility, you can set a seed using np.random.seed().

- Everytime you can run the code with np.random.seed(2),

1.   List item
2.   List item

it will generate the exact same random numbers.

if you remove or change the seed values , the sequence of random number will be changed

In [ ]:
np.random.rand(5)

array([0.06161875, 0.24071444, 0.59518921, 0.78328035, 0.09815704])

In [ ]:
np.random.seed(2)
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [ ]:
np.random.seed(5)
np.random.rand(5, 2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [ ]:
np.random.randn(5, 2)

array([[ 0.18760323, -0.32986996],
       [-1.19276461, -0.20487651],
       [-0.35882895,  0.6034716 ],
       [-1.66478853, -0.70017904],
       [ 1.15139101,  1.85733101]])

In [ ]:
np.random.seed(42)
np.random.randint(low=0, high=100, size=(5, 2))

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

###elemeent wise operation

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [ ]:
# comparision operations
# you can perform element -wise comparisions and create boolen arrays
a

array([0, 1, 2, 3, 4])

In [ ]:
a >= 2

array([False, False,  True,  True,  True])

In [ ]:
a > b

array([False, False, False, False, False])

# New Section

# summaring
#NUmpy provides function for summaring arrays of data

In [ ]:

a

array([0, 1, 2, 3, 4])

In [ ]:
# standard deviation
a.std()

1.4142135623730951

In [ ]:
# min value of array
a.min()

0

In [ ]:
# max value of array
a.max()

4

In [ ]:
# sum of elements of an array
a.sum()

10