<a href="https://colab.research.google.com/github/PCsujan/ML_From_Scratch/blob/main/01_MachineLearning/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np





## introduction to numpy
what will we cover?
- creating arrays
- multi diesional array
- randomly generated array
    - element wise operations
    - coparision operations
-LOGICAL operation

summarizing operation

###single dimensional arrays


# New Section

###Multidimesional Arrays

In [5]:
var = np.zeros(5)
print(type(var))

<class 'numpy.ndarray'>


In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [16]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [21]:
var= np.array([1, 2, 3, 4])
var[2] = 5
var

array([1, 2, 5, 4])

In [22]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

create array with evenly spaced numbers within a specified
range

In [24]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [25]:
np.zeros([5, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
#create a Md unit array of size(5, 2)

np.ones([5, 2])


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
#Generate a random array of size (3, 5)with element of your choice
n = np.random.randint(1, 10, size=(3, 5))

n


array([[6, 2, 2, 8, 3],
       [5, 3, 2, 4, 2],
       [6, 9, 9, 6, 4]])

In [34]:
#upadte the element of array with in index
n[0, 0]= 10
n



array([[10,  2,  2,  8,  3],
       [ 5,  3,  2,  4,  2],
       [ 6,  9,  9,  6,  4]])

In [37]:
n[0] = [1, 1, 1, 1, 1]
n

array([[1, 1, 1, 1, 1],
       [5, 3, 2, 4, 2],
       [6, 9, 9, 6, 4]])

In [40]:
n[:,2] = [2, 2, 2]

n


array([[1, 1, 2, 1, 1],
       [5, 3, 2, 4, 2],
       [6, 9, 2, 6, 4]])

###Randomly generated arrays
- Numpy can cratre array filled with random number.
- To ensure the reproducibility, you can set a seed using np.random.seed().

- Everytime you can run the code with np.random.seed(2),

1.   List item
2.   List item

it will generate the exact same random numbers.

if you remove or change the seed values , the sequence of random number will be changed

In [43]:
np.random.rand(5)

array([0.06161875, 0.24071444, 0.59518921, 0.78328035, 0.09815704])

In [47]:
np.random.seed(2)
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [51]:
np.random.seed(5)
np.random.rand(5, 2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [52]:
np.random.randn(5, 2)

array([[ 0.18760323, -0.32986996],
       [-1.19276461, -0.20487651],
       [-0.35882895,  0.6034716 ],
       [-1.66478853, -0.70017904],
       [ 1.15139101,  1.85733101]])

In [53]:
np.random.seed(42)
np.random.randint(low=0, high=100, size=(5, 2))

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

###elemeent wise operation

In [54]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [56]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [57]:
# comparision operations
# you can perform element -wise comparisions and create boolen arrays
a

array([0, 1, 2, 3, 4])

In [58]:
a >= 2

array([False, False,  True,  True,  True])

In [59]:
a > b

array([False, False, False, False, False])

# summaring
#NUmpy provides function for summaring arrays of data

In [60]:

a

array([0, 1, 2, 3, 4])

In [61]:
# standard deviation
a.std()

1.4142135623730951

In [62]:
# min value of array
a.min()

0

In [64]:
# max value of array
a.max()

4

In [65]:
# sum of elements of an array
a.sum()

10